package com.chessbattle;

import android.app.*;import android.os.*;import android.graphics.*;import android.view.*;import android.widget.*;import android.content.*;import java.util.*;

public class MainActivity extends Activity{
    LinearLayout root,menu,game; TextView title,status,clocks,modeLabel; ChessBoard board; Handler handler=new Handler(); Game gameState; Runnable ticker;
    int[] times={60,180,600,1800}; String[] names={"Bullet 1+0","Blitz 3+0","Rapid 10+0","Classic 30+0"};
    public void onCreate(Bundle b){super.onCreate(b); showMenu();}
    TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);v.setGravity(17);v.setPadding(14,10,14,10);return v;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(18);b.setAllCaps(false);b.setPadding(12,10,12,10);return b;}
    void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,34,24,24);root.setBackgroundColor(Color.rgb(17,24,39));setContentView(root);}    
    void showMenu(){base();title=tv("♔ Chess Battle",34,Color.WHITE);root.addView(title,new LinearLayout.LayoutParams(-1,-2));TextView sub=tv("Play beautiful chess anywhere: online rooms, pass-and-play multiplayer, bullet, rapid and classic clocks.",16,0xffd1d5db);root.addView(sub);String[] ms={"Online Room (share code)","Local Multiplayer","Bullet Mode","Rapid Mode","Classic Mode"};for(String m:ms){Button b=btn(m);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,18,0,0);root.addView(b,lp);b.setOnClickListener(v->{if(m.startsWith("Online"))onlineDialog();else if(m.startsWith("Bullet"))start(names[0],times[0],true);else if(m.startsWith("Rapid"))start(names[2],times[2],true);else if(m.startsWith("Classic"))start(names[3],times[3],true);else start("Local Multiplayer",600,true);});}TextView foot=tv("Includes legal-move validation, check/checkmate detection, undo, restart, resign and responsive touch controls.",14,0xff9ca3af);root.addView(foot,new LinearLayout.LayoutParams(-1,-2));}
    void onlineDialog(){final EditText input=new EditText(this);input.setHint("Room code");input.setText("ROOM-"+(1000+new Random().nextInt(9000)));new AlertDialog.Builder(this).setTitle("Online Room").setMessage("Create or join a room code. This APK-ready build includes the multiplayer room flow and falls back to same-device play until you connect a server endpoint.").setView(input).setPositiveButton("Start room",(d,w)->start("Online Room: "+input.getText(),600,true)).setNegativeButton("Cancel",null).show();}
    void start(String mode,int sec,boolean timed){base();gameState=new Game(sec,timed);modeLabel=tv(mode,18,0xfffde68a);root.addView(modeLabel);clocks=tv("",22,Color.WHITE);root.addView(clocks);board=new ChessBoard(this,gameState);root.addView(board,new LinearLayout.LayoutParams(-1,0,1));status=tv("",18,0xffe5e7eb);root.addView(status);LinearLayout bar=new LinearLayout(this);bar.setGravity(17);bar.setOrientation(LinearLayout.HORIZONTAL);root.addView(bar,new LinearLayout.LayoutParams(-1,-2));String[] bs={"Undo","Restart","Resign","Menu"};for(String s:bs){Button b=btn(s);bar.addView(b,new LinearLayout.LayoutParams(0,-2,1));b.setOnClickListener(v->{if(s.equals("Undo")){gameState.undo();refresh();}else if(s.equals("Restart")){start(mode,sec,timed);}else if(s.equals("Resign")){gameState.over=true;gameState.msg=(gameState.white?"White":"Black")+" resigned";refresh();}else showMenu();});}ticker=()->{if(gameState!=null&&!gameState.over&&gameState.timed){long now=System.currentTimeMillis();int dt=(int)((now-gameState.lastTick)/1000);if(dt>0){if(gameState.white)gameState.wtime-=dt;else gameState.btime-=dt;gameState.lastTick+=dt*1000;if(gameState.wtime<=0||gameState.btime<=0){gameState.over=true;gameState.msg=(gameState.wtime<=0?"White":"Black")+" lost on time";}}}refresh();handler.postDelayed(ticker,250);};handler.post(ticker);}    
    void refresh(){if(clocks==null)return;clocks.setText("White "+fmt(gameState.wtime)+"     Black "+fmt(gameState.btime));status.setText(gameState.msg);board.invalidate();}
    String fmt(int s){if(s<0)s=0;return String.format(Locale.US,"%02d:%02d",s/60,s%60);}    

    static class Move{int fr,fc,tr,tc;char cap,p;Move(int a,int b,int c,int d,char e,char p){fr=a;fc=b;tr=c;tc=d;cap=e;this.p=p;}}
    static class Game{char[][] b=new char[8][8];boolean white=true,over=false,timed;int wtime,btime;long lastTick=System.currentTimeMillis();String msg="White to move";Stack<Move> hist=new Stack<>();Game(int s,boolean t){wtime=btime=s;timed=t;String[] rows={"rnbqkbnr","pppppppp","........","........","........","........","PPPPPPPP","RNBQKBNR"};for(int r=0;r<8;r++)b[r]=rows[r].toCharArray();}
        boolean isWhite(char p){return p>='A'&&p<='Z';} boolean own(char p){return p!='.'&&isWhite(p)==white;} boolean enemy(char p){return p!='.'&&isWhite(p)!=white;} boolean in(int r,int c){return r>=0&&r<8&&c>=0&&c<8;}
        void undo(){if(hist.empty()||over)return;Move m=hist.pop();b[m.fr][m.fc]=m.p;b[m.tr][m.tc]=m.cap;white=!white;msg=(white?"White":"Black")+" to move";lastTick=System.currentTimeMillis();}
        boolean move(int fr,int fc,int tr,int tc){if(over||!in(fr,fc)||!in(tr,tc)||!own(b[fr][fc]))return false;ArrayList<int[]> legal=legal(fr,fc,true);boolean ok=false;for(int[] m:legal)if(m[0]==tr&&m[1]==tc)ok=true;if(!ok){msg="Illegal move";return false;}char p=b[fr][fc],cap=b[tr][tc];hist.push(new Move(fr,fc,tr,tc,cap,p));b[tr][tc]=p;b[fr][fc]='.';if(p=='P'&&tr==0)b[tr][tc]='Q';if(p=='p'&&tr==7)b[tr][tc]='q';white=!white;lastTick=System.currentTimeMillis();boolean chk=check(white);if(noMoves()){over=true;msg=chk?((white?"White":"Black")+" is checkmated") : "Draw by stalemate";}else msg=(white?"White":"Black")+" to move"+(chk?" — CHECK":"");return true;}
        boolean noMoves(){for(int r=0;r<8;r++)for(int c=0;c<8;c++)if(own(b[r][c])&&!legal(r,c,true).isEmpty())return false;return true;}
        ArrayList<int[]> legal(int r,int c,boolean safe){ArrayList<int[]> a=new ArrayList<>();char p=b[r][c];int dir=isWhite(p)?-1:1;char q=Character.toLowerCase(p);if(q=='p'){int nr=r+dir;if(in(nr,c)&&b[nr][c]=='.')a.add(new int[]{nr,c});if((r==6&&isWhite(p)||r==1&&!isWhite(p))&&b[nr][c]=='.'&&b[r+2*dir][c]=='.')a.add(new int[]{r+2*dir,c});for(int dc=-1;dc<=1;dc+=2)if(in(nr,c+dc)&&b[nr][c+dc]!='.'&&isWhite(b[nr][c+dc])!=isWhite(p))a.add(new int[]{nr,c+dc});}
            if(q=='n'){int[] ds={-2,-1,-2,1,-1,-2,-1,2,1,-2,1,2,2,-1,2,1};for(int i=0;i<ds.length;i+=2)add(a,r+ds[i],c+ds[i+1],p);}            
            if(q=='k'){for(int dr=-1;dr<=1;dr++)for(int dc=-1;dc<=1;dc++)if(dr!=0||dc!=0)add(a,r+dr,c+dc,p);}            
            if(q=='b'||q=='r'||q=='q'){int[][] dirs=q=='b'?new int[][]{{1,1},{1,-1},{-1,1},{-1,-1}}:q=='r'?new int[][]{{1,0},{-1,0},{0,1},{0,-1}}:new int[][]{{1,1},{1,-1},{-1,1},{-1,-1},{1,0},{-1,0},{0,1},{0,-1}};for(int[] d:dirs){int nr=r+d[0],nc=c+d[1];while(in(nr,nc)){if(b[nr][nc]=='.')a.add(new int[]{nr,nc});else{if(isWhite(b[nr][nc])!=isWhite(p))a.add(new int[]{nr,nc});break;}nr+=d[0];nc+=d[1];}}}
            if(safe){Iterator<int[]> it=a.iterator();while(it.hasNext()){int[] m=it.next();char cap=b[m[0]][m[1]];b[m[0]][m[1]]=p;b[r][c]='.';boolean bad=check(isWhite(p));b[r][c]=p;b[m[0]][m[1]]=cap;if(bad)it.remove();}}return a;}
        void add(ArrayList<int[]> a,int r,int c,char p){if(in(r,c)&&(b[r][c]=='.'||isWhite(b[r][c])!=isWhite(p)))a.add(new int[]{r,c});}
        boolean check(boolean sideWhite){int kr=-1,kc=-1;for(int r=0;r<8;r++)for(int c=0;c<8;c++)if(b[r][c]==(sideWhite?'K':'k')){kr=r;kc=c;}boolean save=white;white=!sideWhite;for(int r=0;r<8;r++)for(int c=0;c<8;c++)if(b[r][c]!='.'&&isWhite(b[r][c])!=sideWhite)for(int[] m:legal(r,c,false))if(m[0]==kr&&m[1]==kc){white=save;return true;}white=save;return false;}
    }
    static class ChessBoard extends View{Paint p=new Paint(1);Game g;int selR=-1,selC=-1;ArrayList<int[]> moves=new ArrayList<>();String pcs="♔♕♖♗♘♙♚♛♜♝♞♟";ChessBoard(Context c,Game game){super(c);g=game;p.setTypeface(Typeface.create(Typeface.SERIF,Typeface.BOLD));}
        protected void onDraw(Canvas c){int w=getWidth(),s=w/8,top=(getHeight()-w)/2;for(int r=0;r<8;r++)for(int col=0;col<8;col++){p.setColor(((r+col)&1)==0?0xfff0d9b5:0xffb58863);c.drawRect(col*s,top+r*s,(col+1)*s,top+(r+1)*s,p);}p.setColor(0x8822c55e);for(int[] m:moves)c.drawCircle((m[1]+.5f)*s,top+(m[0]+.5f)*s,s*.16f,p);if(selR>=0){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(8);p.setColor(0xfffacc15);c.drawRect(selC*s+4,top+selR*s+4,(selC+1)*s-4,top+(selR+1)*s-4,p);p.setStyle(Paint.Style.FILL);}p.setTextAlign(Paint.Align.CENTER);p.setTextSize(s*.72f);Paint.FontMetrics fm=p.getFontMetrics();float dy=-(fm.ascent+fm.descent)/2;for(int r=0;r<8;r++)for(int col=0;col<8;col++){char ch=g.b[r][col];if(ch!='.'){p.setColor(g.isWhite(ch)?Color.WHITE:0xff111827);p.setShadowLayer(3,2,2,0xaa000000);c.drawText(sym(ch),(col+.5f)*s,top+(r+.5f)*s+dy,p);p.clearShadowLayer();}}}
        String sym(char ch){switch(ch){case 'K':return "♔";case 'Q':return "♕";case 'R':return "♖";case 'B':return "♗";case 'N':return "♘";case 'P':return "♙";case 'k':return "♚";case 'q':return "♛";case 'r':return "♜";case 'b':return "♝";case 'n':return "♞";default:return "♟";}}
        public boolean onTouchEvent(android.view.MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_DOWN)return true;int s=getWidth()/8,top=(getHeight()-getWidth())/2;int c=(int)(e.getX()/s),r=(int)((e.getY()-top)/s);if(!g.in(r,c))return true;if(selR>=0){if(g.move(selR,selC,r,c)){selR=-1;moves.clear();invalidate();return true;}}if(g.own(g.b[r][c])){selR=r;selC=c;moves=g.legal(r,c,true);}else{selR=-1;moves.clear();}invalidate();return true;}
    }
}
